// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFWojvM13XBwa7EmRcw8AUzft3urzXlI',
    appId: '1:994400477277:web:f8a4170404a96586a06db4',
    messagingSenderId: '994400477277',
    projectId: 'travelappbd-8e204',
    authDomain: 'travelappbd-8e204.firebaseapp.com',
    storageBucket: 'travelappbd-8e204.firebasestorage.app',
    measurementId: 'G-HRK09WWJ03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-0WUy2rG3aJYiKo-vACx7G26WWYRzvLc',
    appId: '1:994400477277:android:d19bd770bd131911a06db4',
    messagingSenderId: '994400477277',
    projectId: 'travelappbd-8e204',
    storageBucket: 'travelappbd-8e204.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFWojvM13XBwa7EmRcw8AUzft3urzXlI',
    appId: '1:994400477277:web:64662c2c1b030ccca06db4',
    messagingSenderId: '994400477277',
    projectId: 'travelappbd-8e204',
    authDomain: 'travelappbd-8e204.firebaseapp.com',
    storageBucket: 'travelappbd-8e204.firebasestorage.app',
    measurementId: 'G-KJLCPYB1L2',
  );
}
